version: '3'

services:
  app:
    build: "./forecast_api" # instead of image
    environment:
#      APP_ENV: "prod"
#      APP_DEBUG: "False"
#      APP_PORT: 5000
      MONGODB_DATABASE: flaskdb
      MONGODB_USERNAME: flaskuser
      MONGODB_PASSWORD: password
      MONGODB_HOSTNAME: mongodb
    ports:
      - "5000:5000"
    links:
      - my_db


  my_db:
    build: "./db"

######### add these if authentication is required
#    environment:  
#      - MONGO_INITDB_ROOT_USERNAME=flaskuser
#      - MONGO_INITDB_ROOT_PASSWORD=password
#      MONGO_INITDB_DATABASE: flaskdb
#      MONGODB_DATA_DIR: /data/db
#      MONGODB_LOG_DIR: /dev/null
    volumes:
      - ./mongodbdata:/data/db
